server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
                  #uri: ${HOME}/Documentos/desarrollo/IdeaProjects/spring-config-server
          uri: ${user.home}/Documentos/desarrollo/IdeaProjects/spring-config-server
          #uri: https://github.com/JANCARLO123/spring-config-server/
          clone-on-start: true
          username:
          password:
          search-paths: config-repo
  application:
    name: configserver
